name: Docker Image CI

on:
  push:
    branches: [cicd]
  pull_request:
    branches: [cicd]

jobs:
  build-deploy-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: featch version
        id: v1 
        run: |
         git_hash=$(git rev-parse --short "$GITHUB_SHA")
         versions=${GITHUB_REF##*/}-$git_hash


      - name: Build the Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: shivamsinghgslab/edc-backend
          registry: docker.io
          dockerfile: Dockerfile
          tags: ${{ steps.v1.versions }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            VERSION : ${{ steps.v1.versions }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            docker stop edc-backend-test || true
            docker rmi -f $(docker images -a -q) || true
            # docker rm edc-backend-test || true
            docker run -d --name edc-backend-test -p 3000:3000 shivamsinghgslab/edc-backend-test:${{ env.VERSION }} 
            
          '
